CREATE TABLE climate_change_comments (
    `comment_id` String NOT NULL,
    `score` Int32,
    `self_text` String,
    `subreddit` String,
    `created_time` String,
    `post_id` String NOT NULL,
    `author_name` String,
    `controversiality` String,
    `ups` String,
    `downs` String,
    `user_is_verified` String,
    `user_account_created_time` String,
    `user_awardee_karma` String,
    `user_awarder_karma` String,
    `user_link_karma` String,
    `user_comment_karma` String,
    `user_total_karma` String,
    `post_score` String,
    `post_self_text` String,
    `post_title` String,
    `post_upvote_ratio` String,
    `post_thumbs_ups` String,
    `post_total_awards_received` String,
    `post_created_time` String,
    INDEX `idx_comments` GLOBAL ON (`created_time`),
    INDEX `idx_posts` GLOBAL ON (`post_created_time`),
    PRIMARY KEY (`comment_id`)
);